# Generated by Django 5.0.3 on 2024-03-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/defaultprp.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
