# Generated by Django 4.2.7 on 2024-04-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_post_user_post_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
