# Generated by Django 4.2.7 on 2024-04-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_lectures'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='time',
            field=models.CharField(default='7:00 AM', max_length=32),
        ),
    ]
