# Generated by Django 4.2.7 on 2024-04-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_lectures_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lectures',
            new_name='LecturesIF',
        ),
    ]
