# Generated by Django 4.2.7 on 2025-04-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_complaints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EE',
            new_name='BAF',
        ),
        migrations.RenameModel(
            old_name='CO',
            new_name='BBI',
        ),
        migrations.RenameModel(
            old_name='EJ',
            new_name='BCA',
        ),
        migrations.RenameModel(
            old_name='ME',
            new_name='BMS',
        ),
        migrations.RenameModel(
            old_name='IF',
            new_name='BSC',
        ),
        migrations.RenameModel(
            old_name='LecturesCO',
            new_name='LecturesBAF',
        ),
        migrations.RenameModel(
            old_name='LecturesME',
            new_name='LecturesBBI',
        ),
        migrations.RenameModel(
            old_name='LecturesEJ',
            new_name='LecturesBCA',
        ),
        migrations.RenameModel(
            old_name='LecturesIF',
            new_name='LecturesBMS',
        ),
        migrations.RenameModel(
            old_name='LecturesEE',
            new_name='LecturesBSC',
        ),
    ]
